services:
  ###> doctrine/doctrine-bundle ###
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    env_file:
      - .env.local
    environment:
      PMA_HOST: db_mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - 8080:80
    depends_on:
      - db_mysql
  ###< doctrine/doctrine-bundle ###

  ###> symfony/mailer ###
  mailer:
    image: axllent/mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

###< symfony/mailer ###
